/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js}'],
  theme: {
    extend: {
      colors: {
        'surface-container': '#e5e9eb',
        'tertiary': '#7f448c',
        'on-secondary': '#ffefeb',
        'error-dim': '#a70138',
        'tertiary-container': '#f0abfc',
        'surface-variant': '#d9dde0',
        'tertiary-dim': '#723880',
        'on-tertiary-container': '#5e266d',
        'on-primary': '#f4f1ff',
        'inverse-on-surface': '#9a9d9f',
        'secondary-fixed': '#ffc4b1',
        'primary-dim': '#3939c7',
        'primary-fixed-dim': '#8387ff',
        'background': '#f5f7f9',
        'primary-container': '#9396ff',
        'on-secondary-container': '#832800',
        'surface-container-low': '#eef1f3',
        'on-primary-fixed-variant': '#0e009d',
        'on-primary-fixed': '#000000',
        'on-tertiary-fixed': '#470d56',
        'secondary': '#a03a0f',
        'on-primary-container': '#0a0081',
        'outline-variant': '#abadaf',
        'surface-tint': '#4647d3',
        'surface-dim': '#d0d5d8',
        'surface-container-lowest': '#ffffff',
        'error': '#b41340',
        'surface': '#f5f7f9',
        'surface-container-highest': '#d9dde0',
        'on-background': '#2c2f31',
        'inverse-surface': '#0b0f10',
        'primary-fixed': '#9396ff',
        'surface-bright': '#f5f7f9',
        'on-surface-variant': '#595c5e',
        'on-error': '#ffefef',
        'error-container': '#f74b6d',
        'outline': '#747779',
        'on-tertiary': '#ffeefd',
        'on-tertiary-fixed-variant': '#682f76',
        'inverse-primary': '#8083ff',
        'tertiary-fixed': '#f0abfc',
        'on-surface': '#2c2f31',
        'secondary-fixed-dim': '#ffb196',
        'surface-container-high': '#dfe3e6',
        'on-secondary-fixed': '#621c00',
        'primary': '#4647d3',
        'on-error-container': '#510017',
        'tertiary-fixed-dim': '#e29eee',
        'secondary-dim': '#902e02',
        'on-secondary-fixed-variant': '#922f03',
        'secondary-container': '#ffc4b1',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['"Plus Jakarta Sans"', 'sans-serif'],
        label: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
